# Generated by Django 4.1.3 on 2022-11-10 16:22

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextension',
            name='user_description',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
