# Generated by Django 4.1.3 on 2022-11-09 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_car_fabrication_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='fabrication_date',
            field=models.DateField(),
        ),
    ]
